# Generated by Django 2.0.2 on 2019-05-11 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20190511_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=1000)),
                ('mod_date', models.DateTimeField(verbose_name='Date modified')),
            ],
        ),
    ]
