# Generated by Django 2.0.2 on 2019-05-12 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='body',
            field=models.TextField(default='Body'),
        ),
        migrations.AddField(
            model_name='content',
            name='excerpt',
            field=models.TextField(default='Excerpt'),
        ),
        migrations.AddField(
            model_name='content',
            name='status',
            field=models.CharField(choices=[('Published', 'Published'), ('Draft', 'Draft'), ('Deleted', 'Deleted')], default='Draft', max_length=16),
        ),
        migrations.AlterField(
            model_name='content',
            name='title',
            field=models.TextField(default='Title', max_length=1000),
        ),
    ]
