# Generated by Django 2.0.2 on 2019-05-12 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20190511_2312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='title',
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='Product description'),
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.TextField(default='Product name', max_length=1000),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.CharField(default='$20', max_length=16),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Deleted', 'Deleted')], default='Available', max_length=16),
        ),
    ]
