# Generated by Django 2.2.1 on 2019-05-12 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20190512_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='pages',
            field=models.CharField(choices=[('Team', 'Team'), ('Privacy', 'Privacy'), ('Terms', 'Terms')], default='Team', max_length=16),
        ),
    ]
